server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file://D:/msa_with_spring_cloud_config
          uri: https://github.com/jaeheonYoo325/msa_with_spring_cloud_config.git
#          username: [your username]
#          password: [your password]